### ISSUE TITLE
Bluetooth Audio and Desktop Sound settings don't work because PulseAudio/Pipewire are incompatible

### ISSUE THREAD

**Issue by RodBarnes** [cb-linux/breath#113]
Bluetooth works fine on a stock Ubuntu booted via LEGACY_BOOT.  Via Breath image, it connects and immediately disconnects. Note that this is the virgin image; I have not run `apl-sof-setup-audio` or `sof-setup-audio`. So, pulse audio hasn't yet been removed and the `pulseaudio-module-bluetooth` is currently present.

Maybe there are other things being left out?

Under stock Ubuntu, it is using pulse audio and relying upon `pulseaudio-module-bluetooth` -- see this [article](https://askubuntu.com/questions/1037370/ubuntu-18-04-bluetooth-device-disconnects-right-after-connect-on-lenovo-p50).

@MilkyDeveloper Do you anticipate getting Bluetooth audio working?  Of course, a difference is Breath is based upon the server edition vs desktop.  Maybe there is something there...?

FYI: Bluetooth in general seems to be working since: 1) it attempts to connect then immediately disconnects, and 2) a BT mouse connects and remains connected.

**Comment by RodBarnes** [comment]
Bluetooth in general seems to be working since: 1) it attempts to connect then immediately disconnects, and 2) a BT mouse connects and remains connected.

Attempts to use `bluetoothctl` to investigate haven't been fruitful.  I can connect there but it immediately disconnects with this error: `Failed to connect: org.bluez.Error.failed`.

I do note this difference in output of `bluetoothctl show` -- note that under Breath it doesn't report anything about `Headset`, `Audio Sink` or `Audio Source`.

The stock Ubuntu desktop shows this:
```
[bluetooth]# show
Controller 9C:DA:3E:D7:FE:37 (public)
	Name: sleek
	Alias: sleek
	Class: 0x0000010c
	Powered: yes
	Discoverable: no
	DiscoverableTimeout: 0x000000b4
	Pairable: yes
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d053C
	Discovering: no
	Roles: central
	Roles: peripheral
Advertising Features:
	ActiveInstances: 0x00 (0)
	SupportedInstances: 0x05 (5)
	SupportedIncludes: tx-power
	SupportedIncludes: appearance
	SupportedIncludes: local-name
```
While Breath Ubuntu shows this:
```
[bluetooth]# show
Controller 9C:DA:3E:D7:FE:37 (public)
	Name: ubuntu
	Alias: ubuntu
	Class: 0x007c010c
	Powered: yes
	Discoverable: no
	DiscoverableTimeout: 0x000000b4
	Pairable: yes
	UUID: Message Notification Se.. (00001133-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: OBEX Object Push          (00001105-0000-1000-8000-00805f9b34fb)
	UUID: Message Access Server     (00001132-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: IrMC Sync                 (00001104-0000-1000-8000-00805f9b34fb)
	UUID: Vendor specific           (00005005-0000-1000-8000-0002ee000001)
	UUID: Headset                   (00001108-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Phonebook Access Server   (0000112f-0000-1000-8000-00805f9b34fb)
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: Handsfree Audio Gateway   (0000111f-0000-1000-8000-00805f9b34fb)
	UUID: Audio Source              (0000110a-0000-1000-8000-00805f9b34fb)
	UUID: OBEX File Transfer        (00001106-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d053C
	Discovering: no
	Roles: central
	Roles: peripheral
Advertising Features:
	ActiveInstances: 0x00 (0)
	SupportedInstances: 0x05 (5)
	SupportedIncludes: appearance
	SupportedIncludes: local-name
```

**Comment by MilkyDeveloper** [comment]
Yeah, this is a glaring issue in this project's pure-ALSA audio implementation. Bluez's BT audio and ALSA don't work together. You can use `bluez-alsa` to fix this, but it is pretty hard for the user to configure and use, so I wouldn't recommend it.

This leaves us with only two options: **Pulseaudio** or **Pipewire** (note that ALSA cannot be removed; ALSA is omnipresent in the kernel, but Pulse/PW can replace ALSA in handling the userspace).

PulseAudio is very common, is probably in your Linux desktop, but is hated by some as complicated and slow. Pipewire, on the otherhand, is new, fast, somewhat popular in bleeding-edge distros, but is not well documented at all.

This causes me to lean towards PulseAudio, which is more sophisticated and documented better. However, I have been trying sporadically across the last few months to get Pulse working. I will now shift all of my focus to this.

**Comment by RodBarnes** [comment]
Understood.  Meanwhile, I will continue to investigate options.  I'm going to explore [deb bluetooth-alsa](https://wiki.debian.org/Bluetooth/Alsa)?

**Comment by RodBarnes** [comment]
[This](https://github.com/thesofproject/sof/issues/5361) thread has gotten interesting regarding some use of PulseAudio...

**Comment by MilkyDeveloper** [comment]
I've read it more than once, but it seems like they're only commenting about volume scaling, and plus, their situation is much different then this one. PulseAudio does not detect _any_ devices at all.

**Comment by MilkyDeveloper** [comment]
I will no longer be pursuing this issue. PulseAudio (clearly the worst software to ever exist) burnt my speakers on my personal Chromebook once I got it working. My personal laptop's personal GPU was already fried.

**Comment by RodBarnes** [comment]
@MilkyDeveloper  Oh, man!  So sorry.  ('Guess that explains the donation refund.)  Well, hmmm...  I felt this project had the most promise of any out there for reaching success of a "real" (aka fully operational) Linux replacement on Chromebooks.

**Comment by MilkyDeveloper** [comment]
Well, you are using SOF, which shouldn't have freak errors like those experienced on my (older, non-sof) audio chip. Try installing `pulseaudio` and run

**Comment by RodBarnes** [comment]
@MilkyDeveloper  Should I get a fire extinguisher ready, just in case? :-D

**Comment by MilkyDeveloper** [comment]
No :D. My speakers didn’t catch fire, my left speaker’s membrane popped and it smelled a bit like burning. Sort of like if you give too much bass or volume to a normal speaker. And also, there’s no evidence your kind of SOF sound card exhibits this behavior. Just in case, I’d lower the volume within alsamixer to 6.

**Comment by RodBarnes** [comment]
@MilkyDeveloper Well, it didn't blow-up.  Here's what I'm seeing...

As expected `ulseaudio -k` returned `E: [pulseaudio] main.c: Failed to kill daemon: No such process`

`pulseaudio -vvvv` returned a [lot](https://termbin.com/gyth) and is now sitting at that last line doing nothing.

**Comment by RodBarnes** [comment]
Actually, if I do something that produces audio -- like pressing backspace on an empty terminal, which beeps -- the output of `pulseaudio -vvvv` in the other window repeats the last two lines and sits there.

**Comment by RodBarnes** [comment]
I tried connecting to my head set but got the same results: It connects and then immediately disconnects.

**Comment by MilkyDeveloper** [comment]
This indicates that Pulse is working. Keep your volume low and try to hear some audio from the speakers - preferably using `speaker-test`, or better yet, `mpv.` What does `pulseaudio -v` output? What about `pactl list` once Pulseaudio is started? Is there anything new in `dmesg`

**Comment by RodBarnes** [comment]
UPDATE: I found I also needed to install `pulseaudio-module-bluetooth`.  Things seem to be working pretty well -- but I'm a newb with `pulseaudio`:

- My internal audio appears as "Headphone - Celeron N3350/Penium N4200/Atom E3900 Series Audio Cluster" in Settings > Sound.
- While running `pulseaudio -vvvv` in one terminal, and then another terminal checking `amixer get Master`, I can confirm that moving the "System Volume" slider causes the value of `amixer` to adjust accordingly. 
- While playing an MP3, I can adjust the "Video" volume slider and it adjusts the output volume of the MP3.  NOTE: Scratchy noise while adjusting the volume but then it seems to smooth out as it continues to play.
- I can now connect to my BT audio and it remains connected.  It appears by name in the "Output Device' selector in Settings.
- Minor note: Regardless of output device the [Test] facility doesn't produce any audio.

But this is a big win, I think!

**Comment by MilkyDeveloper** [comment]
Nice!!! Does internal audio work?

**Comment by RodBarnes** [comment]
Yes, the internal audio appears as the Output Device "Headset" listed above.  Not clear why it is listed that way but it works.

So, for APL, is there a benefit to **not** removing `pulseaudio*` as is done in `sof-setup-audio`?  Or is it best to let it remove everything as it does now, and then just reinstall `pulseaudio` and `pulseaudio-module-bluetooth`?

**Comment by MilkyDeveloper** [comment]
No, seems like there's no point in removing PulseAudio on these SOF boards. I've made PulseAudio the default on SOF now. I've edited some stuff in `sof-setup-audio` and now PulseAudio shouldn't be removed on both SOF boards and your Apollo Lake device.

If you don't mind, could you test these new changes by reflashing the ISO (that you already built) and downloading both `sof-setup-audio` and `apl-sof-setup-audio`, making them executable, and copying those to `/usr/bin`? Huge thanks!

**Comment by RodBarnes** [comment]
I think this didn't work as expected.  Script `sof-setup-audio` is checking ONLY_ALSA for empty (line 17) before removing pulseaudio and then again (line 73) before replacing `pulseaudio` with `apulse`.  By introducing an echo/read into the script, I confirmed  ONLY_ALSA is empty, it ends up removing `puselaudio`'

Here's the long explanation of what I encountered during the test.  (NOTE:  I didn't do exactly the test you requested; I'd already moved forward from that image. :-(  But I think this provides the test you wanted.)

I updated my repo from the latest in main (so it should already have those updated scripts, right?), built a new image, and flashed the USB.  I then booted, ran my configuration script -- which ends by running `apl-sof-setup-audio`.  I then rebooted.

After the reboot, I checked Sound Settings and it was not showing any output devices.  I tried to run `pulseaudio -vvvv` and it said it wasn't installed.  I ran 'apt list | grep pulseaudio` which showed that `apt` was aware of them but none of them showed as installed (see below).  So I installed `pulseaudio` and `pulseaudio-module-bluetooth`.  After this, Sound Settings was showing output devices, internal audio was working, and BT audio is working.

```
rod@sleek:~$ pulseaudio -vvvv
Command 'pulseaudio' not found, but can be installed with:
sudo apt install pulseaudio
rod@sleek:~$ sudo apt list | grep pulseaudio

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gstreamer1.0-pulseaudio/impish,now 1.18.5-1ubuntu2 amd64 [installed]
libkf5pulseaudioqt-dev/impish 1.2-2build1 amd64
libkf5pulseaudioqt2-doc/impish 1.2-2build1 all
libkf5pulseaudioqt2/impish 1.2-2build1 amd64
mkchromecast-pulseaudio/impish 0.3.9~git20200902+db2964a-2 all
osspd-pulseaudio/impish 1.3.2-12.2 amd64
pulseaudio-dlna/impish 0.5.3+git20200329-0.1 all
pulseaudio-equalizer/impish-updates 1:15.0+dfsg1-1ubuntu2.2 amd64
pulseaudio-module-bluetooth/impish-updates 1:15.0+dfsg1-1ubuntu2.2 amd64
pulseaudio-module-gsettings/impish-updates 1:15.0+dfsg1-1ubuntu2.2 amd64
pulseaudio-module-jack/impish-updates 1:15.0+dfsg1-1ubuntu2.2 amd64
pulseaudio-module-lirc/impish-updates 1:15.0+dfsg1-1ubuntu2.2 amd64
pulseaudio-module-raop/impish-updates 1:15.0+dfsg1-1ubuntu2.2 amd64
pulseaudio-module-zeroconf/impish-updates 1:15.0+dfsg1-1ubuntu2.2 amd64
pulseaudio-utils/impish-updates 1:15.0+dfsg1-1ubuntu2.2 amd64
pulseaudio/impish-updates,now 1:15.0+dfsg1-1ubuntu2.2 amd64 [residual-config]
squeezelite-pulseaudio/impish 1.9+git20210102.78fef68-3 amd64
xfce4-pulseaudio-plugin/impish 0.4.3-1 amd64

```

**Comment by MilkyDeveloper** [comment]
Should be fixed now, I forgot to delete the statement that remove PA in the postinstall.

**Comment by RodBarnes** [comment]
I see were `debian.sh` and `ubuntu.sh` were modified to stop removing pulseaudio.  But 'sof-setup-audio` still does a purge of pulseaudio on lines 20-21.

**Comment by MilkyDeveloper** [comment]
Oops, sory about that. Should be fixed now.

**Comment by RodBarnes** [comment]
Still not working.  The intent is to have `sof-setup-audio` **not** remove `pulseaudio` when it is invoked by `apl-sof-setup-audio`. 
 Is that correct?  I can get this working but want to confirm that I understand the intended result.

**Comment by MilkyDeveloper** [comment]
Yes, that’s the intended result. I’m horrible at bash :D

**Comment by RodBarnes** [comment]
UPDATE: I've found that simply **not** removing `pulseaudio` (leaving it in place) still doesn't work.  The only thing that works (so far) is to let PulseAudio be removed and then reinstall it after `sof-setup-audio`, then PulseAudio works (though still isn't running at restart; I have to run `pulseaudio -vvvv`.  I suspect there is a reconfigure or reset of some type needed to PulseAudio so am looking into that...

**Comment by MilkyDeveloper** [comment]
So is PulseAudio completely removed? I'm thinking that this works on a fresh image where PulseAudio is unmasked in systemd.

**Comment by MilkyDeveloper** [comment]
This is fixed in the latest commit by explicity installing PA, PA-utils, and PA-module-bluetooth if it is not found.

**Comment by RodBarnes** [comment]
> So when you run the script PulseAudio doesn't work? Or is PA not installed? I'm thinking that this works on a fresh image where PulseAudio is unmasked in systemd.

PulseAudio is installed but doesn't work.  After doing a bit of research, it appears the general thought is, when switching to a new sound card, the best option is to reinstall PulseAudio.  So, that is probably the best route for Breath, too.  So, what you dd to install when not found, is likely the best path forward.  That is what has worked for me.  I will test the new commit.

**Comment by RodBarnes** [comment]
FYI: Change isn't working; It is bypassing that condition `command -v pulseaudio` in the `else` clause.  Are there cases where we **don't** want `pulseaudio` reinstalled?  In my testing, I had just told it to reinstall without checking for it since I knew it had been removed above -- and that worked.

**Comment by RodBarnes** [comment]
UPDATE: I have a branch (which I have not pushed) but where pulseaudio works correctly.  I haven't pushed this since you have a number of changes you've made since that commit and wanted us to discuss how to move forward.  This is branched from commit 8d97c7 and the only change I made was to modify `apl-sof-setup-audio' to install pulseaudio and do the systemctll unmask at the end.  Booting with this image and running `apl-sof-setup-audio` results in working PulseAudio and it is running with each restart.  (I chose to put it in `apl-sof-setup-audio` since I believe this only applies to APL?)  In this model, pulseaudio is getting removed and then reinstalled but, as I noted earlier, this seems to be appropriate when switching the underlying sound firmware/hardware.  In any case, it works.  There may a more elegant way but I've not found it.  At this point, there are a few minor issues we can still look into but it is 95% working.

**Comment by MilkyDeveloper** [comment]
The changes in your PR are what I used to have :D. Anyways, I’m going to merge this.

**Comment by RodBarnes** [comment]
> The changes in your PR are what I used to have :D. Anyways, I’m going to merge this.

Yep, they are.  I don't know why they didn't work the first time.  Undoubtedly, it was operator malfunction.  In any case, this works very well and audio is consistent.

**Comment by MilkyDeveloper** [comment]
I was just wondering, for compatibility with Realtek soundcards, if you removed `/etc/systemd/system/alsa-reload.service` and rebooted, does audio still work?

**Comment by RodBarnes** [comment]
No.  Removing that and then reboot, audio no longer works at all.
