### ISSUE TITLE
FATAL error during setup.sh

### ISSUE THREAD

**Issue by NodeMixaholic** [cb-linux/breath#60]
Hello. I have attempted setup.sh in both Zorin OS 16 Lite and Pop!_OS 20.04 LTS on two separate computers, one (Zorin) tried using different commits, including master commit. The other (Pop) I tried using the master commit only. Same error. Please help with this error! Thanks. 👍🏻 

Possible key line:  ***FATAL: do_vbutil_kernel: Error reading config file.***
```
▄▄▄▄▄▄                                            ▄▄      
██▀▀▀▀██                                  ██      ██      
██    ██   ██▄████   ▄████▄    ▄█████▄  ███████   ██▄████▄
███████    ██▀      ██▄▄▄▄██   ▀ ▄▄▄██    ██      ██▀   ██
██    ██   ██       ██▀▀▀▀▀▀  ▄██▀▀▀██    ██      ██    ██
██▄▄▄▄██   ██       ▀██▄▄▄▄█  ██▄▄▄███    ██▄▄▄   ██    ██
▀▀▀▀▀▀▀    ▀▀         ▀▀▀▀▀    ▀▀▀▀ ▀▀     ▀▀▀▀   ▀▀    ▀▀
┌──────────────────────┐
│Made by MilkyDeveloper│
└──────────────────────┘
What would you like your username to be? (no spaces, backslashes, or special characters)
NodeMixaholic
Installing Dependencies
Reading package lists...
Building dependency tree...
Reading state information...
arch-install-scripts is already the newest version (23-1).
cgpt is already the newest version (0~R81-12871.B-1).
vboot-kernel-utils is already the newest version (0~R81-12871.B-1).
git is already the newest version (1:2.25.1-1ubuntu3.2).
wget is already the newest version (1.20.3-1ubuntu2).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi heif-gdk-pixbuf
  zorin-os-feedback
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 46 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
debootstrap is already the newest version (1.0.118ubuntu1.6).
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi heif-gdk-pixbuf
  zorin-os-feedback
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 46 not upgraded.


FATAL: do_vbutil_kernel: Error reading config file.
```

**Comment by Denisuu** [comment]
I have the same error. I tried on 2 different machines.

**Comment by MilkyDeveloper** [comment]
Fixed! Try recloning the repo. Sorry about this, I recently moved the repository to a new organization account :D

**Comment by NodeMixaholic** [comment]
First off, I would just like to say: thanks for helping. Secondly, I must comment that you forgot to put "wget" in the wget command. Even when I did put it there (tried before, gave me an error that the command for the URL wasnt found) it still had the same error. I have a feeling progress is being made though!

**Comment by MilkyDeveloper** [comment]
Super sorry! Is it fixed now (`git fetch; git pull`)?

**Comment by NodeMixaholic** [comment]
(This) Issue seems to be patched
